# Generated by Django 5.1.5 on 2025-07-18 21:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('simbolo', models.CharField(max_length=10, unique=True)),
                ('sector', models.CharField(blank=True, max_length=100)),
                ('precio_actual', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='Cartera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_total', models.IntegerField()),
                ('costo_promedio', models.FloatField()),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('accion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.accion')),
            ],
        ),
        migrations.CreateModel(
            name='DecisionBot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_decision', models.CharField(choices=[('compra', 'Compra'), ('venta', 'Venta'), ('hold', 'Mantener')], max_length=10)),
                ('motivo', models.TextField()),
                ('score_confianza', models.FloatField()),
                ('precio_objetivo', models.FloatField(blank=True, null=True)),
                ('fecha_decision', models.DateTimeField(auto_now_add=True)),
                ('ejecutada', models.BooleanField(default=False)),
                ('accion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.accion')),
            ],
        ),
        migrations.CreateModel(
            name='Operacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('compra', 'Compra'), ('venta', 'Venta')], max_length=10)),
                ('cantidad', models.IntegerField()),
                ('precio', models.FloatField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('accion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.accion')),
            ],
        ),
    ]
