# Generated by Django 5.1.4 on 2025-10-26 23:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_producto_imagen_1_producto_imagen_2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canal', models.CharField(choices=[('instagram', 'Instagram'), ('mercado_libre', 'Mercado Libre'), ('ecommerce_vipalu', 'E-commerce Vipalú'), ('otro', 'Otro')], max_length=50)),
                ('fecha_venta', models.DateField()),
                ('costo_producto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_venta', models.DecimalField(decimal_places=2, max_digits=10)),
                ('costo_despacho', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('notas', models.TextField(blank=True, null=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.producto')),
            ],
        ),
    ]
