# Generated by Django 4.2.4 on 2025-10-26 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_venta'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='comision_venta',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='venta',
            name='origen',
            field=models.CharField(choices=[('fabricante', 'Fabricante'), ('propia', 'Fabricación Propia')], default='propia', max_length=50),
        ),
    ]
