# Generated by Django 4.2.4 on 2025-10-27 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_venta_comision_venta_venta_origen'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatosContacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.TextField()),
                ('correo_electronico', models.EmailField(max_length=254)),
            ],
        ),
        migrations.AlterField(
            model_name='venta',
            name='canal',
            field=models.CharField(choices=[('instagram', 'Instagram'), ('facebook', 'Facebook'), ('mercado_libre', 'Mercado Libre'), ('ecommerce_vipalu', 'E-commerce Vipalú'), ('otro', 'Otro')], max_length=50),
        ),
    ]
