# Generated by Django 4.2.4 on 2025-10-27 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_datoscontacto_alter_venta_canal'),
    ]

    operations = [
        migrations.AddField(
            model_name='datoscontacto',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
