# Generated by Django 4.2.4 on 2025-11-02 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_datoscontacto_telefono'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='vendedor',
            field=models.CharField(blank=True, choices=[('Marco', 'Marco'), ('Catalina', 'Catalina')], max_length=100, null=True),
        ),
    ]
