# Generated by Django 4.2.4 on 2025-12-26 22:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0008_venta_vendedor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('puede_ver_ventas', models.BooleanField(default=False)),
                ('puede_crear_ventas', models.BooleanField(default=False)),
                ('puede_editar_ventas', models.BooleanField(default=False)),
                ('puede_eliminar_ventas', models.BooleanField(default=False)),
                ('puede_ver_panel_ventas', models.BooleanField(default=False)),
                ('puede_ver_productos', models.BooleanField(default=False)),
                ('puede_crear_productos', models.BooleanField(default=False)),
                ('puede_editar_productos', models.BooleanField(default=False)),
                ('puede_eliminar_productos', models.BooleanField(default=False)),
                ('puede_importar_excel', models.BooleanField(default=False)),
                ('puede_ejecutar_ia', models.BooleanField(default=False)),
                ('puede_ver_carrito', models.BooleanField(default=False)),
                ('puede_procesar_pagos', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='UsuarioPerfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perfil', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.perfil')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
