# Generated by Django 4.2.4 on 2025-12-26 23:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

from django.db import migrations

def copiar_vendedores(apps, schema_editor):
    Venta = apps.get_model('base', 'Venta')
    User = apps.get_model('auth', 'User')

    for venta in Venta.objects.all():
        if venta.vendedor == "Marco":
            venta.vendedor_fk = User.objects.get(username="marco")
        elif venta.vendedor == "Catalina":
            venta.vendedor_fk = User.objects.get(username="ventas")  # ← ajusta si el usuario se llama distinto
        venta.save()

class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0009_perfil_usuarioperfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='vendedor_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(copiar_vendedores),  # ← ESTA LÍNEA ES CLAVE
    ]
