# Generated by Django 4.2.4 on 2026-05-27 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_remove_venta_vendedor_fk_perfil_acceso_panel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fortaleza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='fortalezas_imagenes/')),
                ('video', models.FileField(blank=True, null=True, upload_to='fortalezas_videos/')),
            ],
        ),
    ]
