# Generated by Django 4.2.4 on 2026-05-30 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_oferta'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('comentario', models.TextField(blank=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='testimonios/')),
            ],
        ),
    ]
