# Generated by Django 4.2.4 on 2026-05-30 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_testimonio'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonio',
            name='imagen2',
            field=models.ImageField(blank=True, null=True, upload_to='testimonios/'),
        ),
        migrations.AlterField(
            model_name='testimonio',
            name='imagen',
            field=models.ImageField(upload_to='testimonios/'),
        ),
    ]
