# Generated by Django 4.2.4 on 2026-06-12 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_testimonio_imagen2_alter_testimonio_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pieza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('stock', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='MovimientoStockPieza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('cantidad', models.IntegerField()),
                ('motivo', models.CharField(blank=True, max_length=200)),
                ('pieza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.pieza')),
            ],
        ),
        migrations.CreateModel(
            name='ConfiguracionProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_necesaria', models.IntegerField()),
                ('pieza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.pieza')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.producto')),
            ],
        ),
    ]
