# Generated by Django 4.2.4 on 2026-06-17 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_orden_ordenitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuiebreStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_faltante', models.IntegerField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.orden')),
                ('pieza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.pieza')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.producto')),
            ],
        ),
    ]
