# Generated by Django 4.2.4 on 2026-06-17 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_orden_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiebrestock',
            name='resuelto',
            field=models.BooleanField(default=False),
        ),
    ]
