# Generated by Django 4.2.4 on 2026-06-17 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0024_orden_codigo_seguimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orden',
            name='codigo_seguimiento',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
