# Generated by Django 4.2.4 on 2026-06-18 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0025_alter_orden_codigo_seguimiento'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductoVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=200)),
                ('url', models.URLField(help_text='URL del video (Reel, YouTube, etc.)')),
                ('orden', models.PositiveIntegerField(default=0)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='base.producto')),
            ],
        ),
    ]
