# Generated by Django 4.2.4 on 2026-06-18 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0026_productovideo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productovideo',
            name='url',
        ),
        migrations.AddField(
            model_name='productovideo',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='videos_productos/'),
        ),
    ]
