# Generated by Django 4.2.4 on 2026-06-22 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0028_beneficioproducto'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsoRealProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='usos_reales/')),
                ('video', models.FileField(blank=True, null=True, upload_to='usos_reales/')),
                ('orden', models.PositiveIntegerField(default=0)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usos_reales', to='base.producto')),
            ],
        ),
    ]
