# Generated by Django 4.2.4 on 2026-06-22 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0029_usorealproducto'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreguntaFrecuenteProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregunta', models.CharField(max_length=255)),
                ('respuesta', models.TextField()),
                ('orden', models.PositiveIntegerField(default=0)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preguntas_frecuentes', to='base.producto')),
            ],
        ),
    ]
