# Generated by Django 4.2.4 on 2026-06-22 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0030_preguntafrecuenteproducto'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductoRelacionado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='productos_relacionados/')),
                ('titulo', models.CharField(max_length=255)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos_relacionados', to='base.producto')),
                ('producto_destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relacionado_destino', to='base.producto')),
            ],
        ),
    ]
