# Generated by Django 4.2.4 on 2026-07-13 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0032_alter_producto_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='stock_comercial',
            field=models.IntegerField(default=0),
        ),
    ]
