# Generated by Django 4.2.4 on 2026-07-23 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0034_rutaentrega_transportista_rutaorden_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PixelEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(max_length=200)),
                ('category', models.CharField(blank=True, max_length=200, null=True)),
                ('element', models.CharField(blank=True, max_length=200, null=True)),
                ('visitor_id', models.CharField(max_length=200)),
                ('session_id', models.CharField(max_length=200)),
                ('page', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('value_number', models.FloatField(blank=True, null=True)),
                ('value_text', models.CharField(blank=True, max_length=500, null=True)),
                ('data', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
