# Generated by Django 4.2.4 on 2026-08-03 00:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0037_region_alter_comuna_nombre_comuna_region_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.region'),
        ),
    ]
